export const lifecycleConformanceCases = [
  {
    id: "fresh.init",
    origin: "fresh",
    operation: "init",
    ownership: "pactile-owned",
    faultPhase: "none",
    expected: "completed",
  },
  {
    id: "legacy.import",
    origin: "legacy",
    operation: "import",
    ownership: "foreign",
    faultPhase: "none",
    expected: "completed-source-preserved",
  },
  {
    id: "mixed.update",
    origin: "mixed",
    operation: "update",
    ownership: "foreign",
    faultPhase: "none",
    expected: "completed-legacy-preserved",
  },
  {
    id: "repeat.reconcile",
    origin: "canonical",
    operation: "reconcile",
    ownership: "pactile-owned",
    faultPhase: "none",
    expected: "idempotent",
  },
  {
    id: "modified.detach",
    origin: "canonical",
    operation: "detach",
    ownership: "modified",
    faultPhase: "none",
    expected: "user-change-preserved",
  },
  {
    id: "borrowed.detach",
    origin: "canonical",
    operation: "detach",
    ownership: "borrowed",
    faultPhase: "none",
    expected: "external-asset-preserved",
  },
  {
    id: "safe.uninstall",
    origin: "canonical",
    operation: "uninstall",
    ownership: "user-state",
    faultPhase: "none",
    expected: "inactive-user-state-preserved",
  },
  {
    id: "sealed.rollback",
    origin: "canonical",
    operation: "rollback",
    ownership: "sealed-generation",
    faultPhase: "none",
    expected: "older-active-newer-preserved",
  },
  {
    id: "detached.reinstall",
    origin: "canonical",
    operation: "reinstall",
    ownership: "shared",
    faultPhase: "none",
    expected: "active-projections-restored",
  },
  {
    id: "stale.purge-preview",
    origin: "canonical",
    operation: "purge",
    ownership: "user-state",
    faultPhase: "after-preview",
    expected: "conflict-no-delete",
  },
  {
    id: "fault.before-canonical-commit",
    origin: "fresh",
    operation: "init",
    ownership: "pactile-owned",
    faultPhase: "before-canonical-commit",
    expected: "interrupted-no-projection",
  },
  {
    id: "fault.adapter-retry",
    origin: "fresh",
    operation: "init",
    ownership: "shared",
    faultPhase: "before-adapter",
    expected: "degraded-then-recovered",
  },
] as const;

export type LifecycleConformanceCase =
  (typeof lifecycleConformanceCases)[number];
