import { defineTileContent, loadTileContent } from "../source.js";

export const ONDEMAND_TILE_IDS = [
  "define-extended",
  "independent-check",
  "worker-orchestration",
  "parent-child",
  "debug-recovery",
  "session-transfer",
  "spec-learning",
  "vcs-integration",
  "personal-memory",
  "retention-storage",
  "retrieval-extended",
] as const;

export const ONDEMAND_TILE_CONTENT = [
  defineTileContent({
    id: "define-extended",
    title: "Define Extended",
    summary: "Resolve ambiguous product choices before complex execution.",
    body: "Explore competing approaches, risks, and invariants, then reduce them to one reviewable definition with explicit tradeoffs.",
    intents: ["semantic", "structural"],
    inputs: ["task.definition"],
    outputs: ["task.design"],
    dependencies: ["define-basic"],
    cost: "low",
    evidenceDescription: "Reference the design decision and rejected alternatives.",
  }),
  defineTileContent({
    id: "independent-check",
    title: "Independent Check",
    summary: "Audit the candidate from evidence independent of the implementer.",
    body: "Reconstruct scope and acceptance from source, diff, and validation evidence. Report blockers separately from nits and do not silently fix the candidate.",
    intents: ["exact", "structural"],
    inputs: ["verification.evidence"],
    outputs: ["review.verdict"],
    dependencies: ["verify-basic"],
    process: "execute",
    evidenceDescription: "Record the independent verdict and reviewed change set.",
  }),
  defineTileContent({
    id: "worker-orchestration",
    title: "Worker Orchestration",
    summary: "Coordinate independent write sets through explicit ownership.",
    body: "Dispatch only bounded work, prevent overlapping ownership, and require a handoff before integration. The parent owns shared glue and final acceptance.",
    intents: ["structural"],
    inputs: ["agent.dispatch", "approval.boundary"],
    outputs: ["worker.handoff"],
    dependencies: ["execute-agent"],
    filesystem: "write",
    process: "execute",
    cost: "medium",
    evidenceKind: "trace-event",
    evidenceDescription: "Record worker ownership, base, and handoff evidence.",
  }),
  defineTileContent({
    id: "parent-child",
    title: "Parent Child",
    summary: "Decompose work and integrate accepted child results once.",
    body: "Keep child scope, base, state, and evidence explicit. Only the parent changes shared integration surfaces and advances accepted results.",
    intents: ["structural"],
    inputs: ["worker.handoff"],
    outputs: ["integration.candidate"],
    dependencies: ["worker-orchestration"],
    filesystem: "write",
    process: "execute",
    cost: "medium",
    evidenceDescription: "Reference accepted child handoffs and integration state.",
  }),
  defineTileContent({
    id: "debug-recovery",
    title: "Debug Recovery",
    summary: "Recover from a reproduced failure without widening the task.",
    body: "Preserve the failing evidence, identify the smallest root cause, repair at the correct seam, and add only the regression proof that protects it.",
    intents: ["exact", "structural"],
    inputs: ["execution.result"],
    outputs: ["debug.recovery"],
    dependencies: ["execute-agent"],
    filesystem: "write",
    process: "execute",
    cost: "medium",
    evidenceKind: "command-result",
    evidenceDescription: "Record the reproduction and post-fix regression result.",
  }),
  defineTileContent({
    id: "session-transfer",
    title: "Session Transfer",
    summary: "Transfer compact, verifiable state across sessions.",
    body: "Carry the goal, authorization, immutable refs, dirty state, completed evidence, and next action. Require live verification before new execution.",
    intents: ["exact", "semantic"],
    inputs: ["context.pack"],
    outputs: ["session.handoff"],
    dependencies: ["context-progressive"],
    filesystem: "write",
    evidenceKind: "artifact",
    evidenceDescription: "Reference the portable handoff and immutable base.",
  }),
  defineTileContent({
    id: "spec-learning",
    title: "Spec Learning",
    summary: "Promote only durable, reusable lessons into project guidance.",
    body: "Distinguish one-off task evidence from stable project rules. Update durable guidance only when authorized and keep implementation facts in code or tests.",
    intents: ["semantic"],
    inputs: ["close.outcome"],
    outputs: ["learning.decision"],
    dependencies: ["close-basic"],
    filesystem: "write",
    evidenceDescription: "Record the durable-learning decision and rationale.",
  }),
  defineTileContent({
    id: "vcs-integration",
    title: "VCS Integration",
    summary: "Finalize and integrate version-control state under a separate grant.",
    body: "Verify the exact candidate, preserve unrelated dirty files, and use non-force integration. Commit, push, merge, and release remain separately authorized actions.",
    intents: ["exact", "structural"],
    inputs: ["vcs.write", "verification.evidence"],
    outputs: ["vcs.result"],
    dependencies: ["verify-basic"],
    filesystem: "write",
    process: "execute",
    cost: "low",
    evidenceKind: "command-result",
    evidenceDescription: "Record exact refs, candidate tree, and integration result.",
  }),
  defineTileContent({
    id: "personal-memory",
    title: "Personal Memory",
    summary: "Retain compact user-specific continuity without secrets.",
    body: "Store only reusable preferences and decisions that the user authorizes. Keep volatile snapshots dated and exclude credentials or private payloads.",
    intents: ["semantic"],
    inputs: ["memory.store", "context.pack"],
    outputs: ["memory.entry"],
    dependencies: ["context-progressive"],
    filesystem: "write",
    evidenceDescription: "Reference the authorized memory update decision.",
  }),
  defineTileContent({
    id: "retention-storage",
    title: "Retention Storage",
    summary: "Apply explicit retention and cleanup boundaries to artifacts.",
    body: "Separate durable evidence from transient transport artifacts. Delete or archive only exact authorized targets and report recoverability.",
    intents: ["exact"],
    inputs: ["close.outcome", "memory.entry"],
    outputs: ["retention.result"],
    dependencies: ["close-basic", "personal-memory"],
    filesystem: "write",
    evidenceKind: "artifact",
    evidenceDescription: "Record retained and removed artifact identities.",
  }),
  defineTileContent({
    id: "retrieval-extended",
    title: "Retrieval Extended",
    summary: "Request authorized semantic, structural, or external retrieval.",
    body: "Express the retrieval intent and evidence requirement without selecting a provider. Treat adapter output as a candidate until current source corroborates it.",
    intents: ["semantic", "structural", "external"],
    inputs: ["retrieval.provider", "context.pack"],
    outputs: ["retrieval.evidence"],
    dependencies: ["context-progressive"],
    process: "execute",
    credentials: "project-authorized",
    network: "project-authorized",
    privacy: "project-approved-egress",
    destinations: ["authorized-provider"],
    cost: "medium",
    evidenceDescription: "Corroborate provider candidates with current source evidence.",
  }),
] as const;

export function loadOndemandTileContent(): ReturnType<typeof loadTileContent> {
  return loadTileContent(ONDEMAND_TILE_CONTENT);
}
