import { defineTileContent, loadTileContent } from "../source.js";

export const ONDEMAND_TILE_IDS = [
  "define-extended",
  "independent-check",
  "worker-orchestration",
  "parent-child",
  "debug-recovery",
  "session-transfer",
  "spec-learning",
  "vcs-integration",
  "personal-memory",
  "retention-storage",
  "retrieval-extended",
] as const;

/** Kept in the bundled catalog for explicit V1 compatibility, not V2 selection. */
export const LEGACY_ONLY_ONDEMAND_TILE_IDS: readonly string[] = ["parent-child"];

export const ONDEMAND_TILE_CONTENT = [
  defineTileContent({
    id: "define-extended",
    title: "Define Extended",
    summary: "Resolve ambiguous product choices before complex execution.",
    body: "Use for unresolved product choices, risky boundaries or competing approaches. Inspect existing facts and applicable research before asking; record decisions and minimal sufficient design without imposing a Task intensity or document quota. Stop for a blocking user decision. Load `.pactile/modules/define-extended/contract.md` and its planning guide only when needed.",
    intents: ["semantic", "structural"],
    inputs: ["task.definition"],
    outputs: ["task.design"],
    dependencies: ["define-basic"],
    cost: "low",
    evidenceDescription: "Reference the design decision and rejected alternatives.",
  }),
  defineTileContent({
    id: "independent-check",
    title: "Independent Check",
    summary: "Audit the candidate from evidence independent of the implementer.",
    body: "Reconstruct the latest completed Run's exact candidate from its definition, diff and evidence. Check requirements, code quality and material risks; report blockers separately from nits without fixing the candidate. Preserve reviewer capabilities but require the task's actual read-only action boundary; prompts alone do not enforce it. Load `.pactile/modules/independent-check/contract.md`; extra depth does not replace the Kernel Review gate.",
    intents: ["exact", "structural"],
    inputs: ["verification.evidence"],
    outputs: ["review.verdict"],
    dependencies: ["verify-basic"],
    process: "execute",
    evidenceDescription: "Record the independent verdict and reviewed change set.",
  }),
  defineTileContent({
    id: "worker-orchestration",
    title: "Worker Orchestration",
    summary: "Coordinate independent write sets through explicit ownership.",
    body: "Bind workers to an approved Task and role. Use Task/Run critical-path scheduling: dispatch concurrently only when it improves completion time and dependencies, write sets, authorization, and isolation permit it. Preserve Pi default capabilities while constraining actions to the role and approved scope. The default RPC does not provide role-action enforcement or an OS sandbox; dispatch requiring that protection needs verified host or external controls. Review stays independent and bound to the exact candidate; Kernel owns Close. Load .pactile/modules/worker-orchestration/contract.md and .pactile/framework/parallel-first-execution.md only when dispatch is needed.",
    intents: ["structural"],
    inputs: ["agent.dispatch", "approval.boundary"],
    outputs: ["worker.handoff"],
    dependencies: ["execute-agent"],
    filesystem: "write",
    process: "execute",
    cost: "medium",
    evidenceKind: "trace-event",
    evidenceDescription: "Record worker ownership, base, and handoff evidence.",
  }),
  defineTileContent({
    id: "parent-child",
    title: "Parent Child",
    summary: "Maintain Parent/Child records only for explicit legacy V1 Tasks.",
    body: "Legacy V1 only: read `.pactile/modules/parent-child/contract.md` after the unified reader identifies that schema. Confirm a decomposition proposal before creating Child records and preserve their original integration evidence. V2 uses independent deliverable Tasks and hard dependencies; this Tile is not a V2 candidate and grants no parent authority.",
    intents: ["structural"],
    inputs: ["worker.handoff"],
    outputs: ["integration.candidate"],
    dependencies: ["worker-orchestration"],
    filesystem: "write",
    process: "execute",
    cost: "medium",
    evidenceDescription: "Reference accepted child handoffs and integration state.",
  }),
  defineTileContent({
    id: "debug-recovery",
    title: "Debug Recovery",
    summary: "Recover from a reproduced failure without widening the task.",
    body: "Use after a reproduced failure or repeated stalled hypothesis. Preserve evidence, separate implementation/contract/environment causes and take the smallest justified next check. Retry with a new Run; do not overwrite failed attempts or invent a V2 Return-to-Define transition. Stop for changed scope or unavailable required protection. Load `.pactile/modules/debug-recovery/contract.md`.",
    intents: ["exact", "structural"],
    inputs: ["execution.result"],
    outputs: ["debug.recovery"],
    dependencies: ["execute-agent"],
    filesystem: "write",
    process: "execute",
    cost: "medium",
    evidenceKind: "command-result",
    evidenceDescription: "Record the reproduction and post-fix regression result.",
  }),
  defineTileContent({
    id: "session-transfer",
    title: "Session Transfer",
    summary: "Transfer compact, verifiable state across sessions.",
    body: "When changing sessions, carry the Task/Run/candidate identities, authorization scope, worktree and dirty state, verified evidence, assumptions and next action. Re-read current Kernel and source before acting; a handoff grants no new execution or Git permission. Write only to an authorized handoff destination. Load `.pactile/modules/session-transfer/contract.md`.",
    intents: ["exact", "semantic"],
    inputs: ["context.pack"],
    outputs: ["session.handoff"],
    dependencies: ["context-progressive"],
    filesystem: "write",
    evidenceKind: "artifact",
    evidenceDescription: "Reference the portable handoff and immutable base.",
  }),
  defineTileContent({
    id: "spec-learning",
    title: "Spec Learning",
    summary: "Promote only durable, reusable lessons into project guidance.",
    body: "Use when a lesson changes future project decisions. Keep one-off evidence in the Task; propose a small update to existing guidance and obtain or reuse scoped authorization before writing. Missing confirmation cannot become permission. Learning notes do not add a Kernel Close gate. Load `.pactile/modules/spec-learning/contract.md`.",
    intents: ["semantic"],
    inputs: ["close.outcome"],
    outputs: ["learning.decision"],
    dependencies: ["close-basic"],
    filesystem: "write",
    evidenceDescription: "Record the durable-learning decision and rationale.",
  }),
  defineTileContent({
    id: "vcs-integration",
    title: "VCS Integration",
    summary: "Finalize and integrate version-control state under a separate grant.",
    body: "Use for delivery requiring Git/PR/merge or managed worktree integration/cleanup. Check exact candidate and current refs, preserve dirty work, and reuse explicit Git grants. `pactile worktree integrate` checks existing integration; it does not merge. Reclaim only through the manager's stop, integration and Close gates. Load `.pactile/modules/vcs-integration/contract.md`.",
    intents: ["exact", "structural"],
    inputs: ["vcs.write", "verification.evidence"],
    outputs: ["vcs.result"],
    dependencies: ["verify-basic"],
    filesystem: "write",
    process: "execute",
    cost: "low",
    evidenceKind: "command-result",
    evidenceDescription: "Record exact refs, candidate tree, and integration result.",
  }),
  defineTileContent({
    id: "personal-memory",
    title: "Personal Memory",
    summary: "Retain compact user-specific continuity without secrets.",
    body: "Use for authorized durable preferences or continuity that current Task artifacts cannot supply. Query the existing journal narrowly; write only the approved scope, date volatile facts and exclude secrets. Do not claim automatic Close notes or inject the whole journal. Load `.pactile/modules/personal-memory/contract.md` for actual journal entry points.",
    intents: ["semantic"],
    inputs: ["memory.store", "context.pack"],
    outputs: ["memory.entry"],
    dependencies: ["context-progressive"],
    filesystem: "write",
    evidenceDescription: "Reference the authorized memory update decision.",
  }),
  defineTileContent({
    id: "retention-storage",
    title: "Retention Storage",
    summary: "Apply explicit retention and cleanup boundaries to artifacts.",
    body: "Use when an artifact's retention expires or storage needs cleanup. Resolve exact authorized targets and recoverability; preserve Kernel evidence, user changes and resources still in use. Task retention and managed Run worktree reclamation have separate contracts. Stop if no supported state-preserving operation exists. Load `.pactile/modules/retention-storage/contract.md`.",
    intents: ["exact"],
    inputs: ["close.outcome", "memory.entry"],
    outputs: ["retention.result"],
    dependencies: ["close-basic", "personal-memory"],
    filesystem: "write",
    evidenceKind: "artifact",
    evidenceDescription: "Record retained and removed artifact identities.",
  }),
  defineTileContent({
    id: "retrieval-extended",
    title: "Retrieval Extended",
    summary: "Rank and pack already collected evidence without collecting it.",
    body: "Use for ranking or packing already collected multi-source evidence, or an authorized retrieval evaluation. Intent planning remains with context-progressive and provider routing with Middleware; pack output alone cannot satisfy an AC. Preserve project egress policy and report unavailable providers honestly. Load `.pactile/modules/retrieval-extended/contract.md` for the Node pack command and frozen ABI.",
    intents: ["semantic", "structural", "external"],
    inputs: ["retrieval.provider", "context.pack"],
    outputs: ["retrieval.evidence"],
    dependencies: ["context-progressive"],
    process: "execute",
    credentials: "project-authorized",
    network: "project-authorized",
    privacy: "project-approved-egress",
    destinations: ["authorized-provider"],
    cost: "medium",
    evidenceDescription: "Corroborate provider candidates with current source evidence.",
  }),
] as const;

export function loadOndemandTileContent(): ReturnType<typeof loadTileContent> {
  return loadTileContent(ONDEMAND_TILE_CONTENT);
}
