import { defineTileContent, loadTileContent } from "../source.js";

export const BASELINE_TILE_IDS = [
  "intake-basic",
  "define-basic",
  "approval-personal",
  "execute-agent",
  "verify-basic",
  "close-basic",
  "context-progressive",
  "observability-local",
] as const;

export const BASELINE_TILE_CONTENT = [
  defineTileContent({
    id: "intake-basic",
    title: "Intake Basic",
    summary: "Turn the request into an explicit, bounded work scope.",
    body: "Clarify only choices that change the outcome. Preserve explicit scope and authorization boundaries, then hand a compact request scope to definition.",
    intents: ["exact", "semantic"],
    outputs: ["request.scope"],
    evidenceDescription: "Record the user request and the resolved scope.",
  }),
  defineTileContent({
    id: "define-basic",
    title: "Define Basic",
    summary: "Define requirements, acceptance evidence, and non-goals.",
    body: "Convert the request into observable acceptance criteria and name non-goals; keep implementation steps separate.\n\nBefore choosing an implementation, use `.pactile/framework/reuse-first-guide.md`: inspect existing capabilities and permitted mature external options; cite applicable prior research, explicit from-scratch instructions or research limits. Record Decision/Rationale/Risk in Task `design.md`. This grants no new permissions.",
    intents: ["exact", "semantic"],
    inputs: ["request.scope"],
    outputs: ["task.definition"],
    dependencies: ["intake-basic"],
    evidenceDescription: "Point to the accepted task definition.",
  }),
  defineTileContent({
    id: "approval-personal",
    title: "Approval Personal",
    summary: "Keep execution and high-impact actions inside user authorization.",
    body: "Treat planning, execution, Git finalization, remote writes, and release actions as distinct grants. Stop when a required grant is absent.",
    intents: ["exact"],
    inputs: ["task.definition"],
    outputs: ["approval.boundary"],
    dependencies: ["define-basic"],
    evidenceKind: "human-approval",
    evidenceDescription: "Retain the explicit approval evidence for the action.",
  }),
  defineTileContent({
    id: "execute-agent",
    title: "Execute Agent",
    summary: "Implement the approved change inside the frozen write set.",
    body: "Make the smallest coherent implementation, preserve unrelated work, and stop if the public contract or authorized scope must change.\n\nApply Task `design.md` and `.pactile/framework/reuse-first-guide.md`. Assess permitted alternatives if a decision is missing; refresh changed facts only. Prefer suitable reuse with a small adapter, or justify self-build. Disclose research limits and preserve installation, network and privacy authority.",
    intents: ["exact", "semantic", "structural"],
    inputs: ["approval.boundary"],
    outputs: ["execution.result"],
    dependencies: ["approval-personal"],
    filesystem: "write",
    process: "execute",
    cost: "low",
    evidenceKind: "artifact",
    evidenceDescription: "Identify the implemented artifact and scoped diff.",
  }),
  defineTileContent({
    id: "verify-basic",
    title: "Verify Basic",
    summary: "Verify observable behavior at pre-agreed public seams.",
    body: "Run change-driven checks, distinguish new failures from baseline debt, and preserve evidence for each acceptance criterion.\n\nUse `.pactile/framework/reuse-first-guide.md` to review choice, evidence and maintenance cost. Check integration behavior; dependency or search counts are not quality proof. Justified self-build and disclosed research limits can be valid. Do not repeat unchanged research without a concrete reason.",
    intents: ["exact", "structural"],
    inputs: ["execution.result"],
    outputs: ["verification.evidence"],
    dependencies: ["execute-agent"],
    process: "execute",
    cost: "low",
    evidenceKind: "command-result",
    evidenceDescription: "Record focused validation results and unresolved failures.",
  }),
  defineTileContent({
    id: "close-basic",
    title: "Close Basic",
    summary: "Close only after acceptance evidence and boundary checks agree.",
    body: "Summarize the outcome, known debt, dirty-state preservation, and separately gated next actions without implying unperformed release work.",
    intents: ["exact"],
    inputs: ["verification.evidence"],
    outputs: ["close.outcome"],
    dependencies: ["verify-basic"],
    filesystem: "write",
    process: "execute",
    evidenceDescription: "Link acceptance evidence and the final scoped outcome.",
  }),
  defineTileContent({
    id: "context-progressive",
    title: "Context Progressive",
    summary: "Load only the context needed for the next decision.",
    body: "Start from indexes and contracts, retrieve deeper source evidence on demand, and carry forward compact state rather than replaying the whole workspace.",
    intents: ["exact", "semantic", "structural"],
    inputs: ["request.scope"],
    outputs: ["context.pack"],
    dependencies: ["intake-basic"],
    evidenceDescription: "Reference the current source or task artifact used.",
  }),
  defineTileContent({
    id: "observability-local",
    title: "Observability Local",
    summary: "Record local, secret-safe execution and decision evidence.",
    body: "Capture deterministic event and result summaries. Never persist credentials, raw sensitive output, or unrelated user content.",
    intents: ["exact", "structural"],
    inputs: ["execution.result"],
    outputs: ["trace.event"],
    dependencies: ["execute-agent"],
    filesystem: "write",
    evidenceKind: "trace-event",
    evidenceDescription: "Persist a sanitized trace event for the observed action.",
  }),
] as const;

export function loadBaselineTileContent(): ReturnType<typeof loadTileContent> {
  return loadTileContent(BASELINE_TILE_CONTENT);
}
