import { defineTileContent, loadTileContent } from "../source.js";

export const BASELINE_TILE_IDS = [
  "intake-basic",
  "define-basic",
  "approval-personal",
  "execute-agent",
  "verify-basic",
  "close-basic",
  "context-progressive",
  "observability-local",
] as const;

export const BASELINE_TILE_CONTENT = [
  defineTileContent({
    id: "intake-basic",
    title: "Intake Basic",
    summary: "Scope new work before creating an independently acceptable Task.",
    body: "Answer directly when no work is requested. Otherwise propose one independently acceptable deliverable, measurable ACs, a delivery level and known hard dependencies. Inspect facts before asking for decisions; create the Task only after user agreement. Load `.pactile/modules/intake-basic/contract.md` for intake boundaries.",
    intents: ["exact", "semantic"],
    outputs: ["request.scope"],
    evidenceDescription: "Record the user request and the resolved scope.",
  }),
  defineTileContent({
    id: "define-basic",
    title: "Define Basic",
    summary: "Define a Task deliverable, acceptance, delivery level and dependencies.",
    body: "Record deliverable, measurable ACs, delivery level and hard dependencies in the Kernel; Markdown explains them without changing gates. Before choosing an implementation, apply `.pactile/framework/reuse-first-guide.md`: reuse capabilities and permitted mature options, or justify self-build; disclose research limits. Record Decision/Rationale/Risk in `design.md`. Load `.pactile/modules/define-basic/contract.md` for changes.",
    intents: ["exact", "semantic"],
    inputs: ["request.scope"],
    outputs: ["task.definition"],
    dependencies: ["intake-basic"],
    evidenceDescription: "Point to the accepted task definition.",
  }),
  defineTileContent({
    id: "approval-personal",
    title: "Approval Personal",
    summary: "Keep execution and high-impact actions inside user authorization.",
    body: "Reuse an existing user grant within its scope. Planning, execution, Git finalization, remote writes and release have distinct boundaries. Record Run authorization; flags and records do not authenticate the user or expand permission. Stop on a missing grant or changed scope. Load `.pactile/modules/approval-personal/contract.md` when a decision needs authorization.",
    intents: ["exact"],
    inputs: ["task.definition"],
    outputs: ["approval.boundary"],
    dependencies: ["define-basic"],
    evidenceKind: "human-approval",
    evidenceDescription: "Retain the explicit approval evidence for the action.",
  }),
  defineTileContent({
    id: "execute-agent",
    title: "Execute Agent",
    summary: "Implement the approved change inside the frozen write set.",
    body: "Implement only an authorized, admitted Run inside its frozen write set; preserve unrelated work and prior attempts. Apply Task `design.md` and `.pactile/framework/reuse-first-guide.md`; refresh changed facts only, prefer suitable reuse or justify self-build. Stop if scope or the public contract changes. Load `.pactile/modules/execute-agent/contract.md` for Run results and retry boundaries.",
    intents: ["exact", "semantic", "structural"],
    inputs: ["approval.boundary"],
    outputs: ["execution.result"],
    dependencies: ["approval-personal"],
    filesystem: "write",
    process: "execute",
    cost: "low",
    evidenceKind: "artifact",
    evidenceDescription: "Identify the implemented artifact and scoped diff.",
  }),
  defineTileContent({
    id: "verify-basic",
    title: "Verify Basic",
    summary: "Verify observable behavior at pre-agreed public seams.",
    body: "Verify the latest completed Run's exact candidate and every AC using risk-driven checks. Use `.pactile/framework/reuse-first-guide.md` to assess actual integration and maintenance cost; do not repeat unchanged research. An independent reviewer reports without fixing the candidate. Missing or stale evidence blocks acceptance. Load `.pactile/modules/verify-basic/contract.md` for Review and validation boundaries.",
    intents: ["exact", "structural"],
    inputs: ["execution.result"],
    outputs: ["verification.evidence"],
    dependencies: ["execute-agent"],
    process: "execute",
    cost: "low",
    evidenceKind: "command-result",
    evidenceDescription: "Record focused validation results and unresolved failures.",
  }),
  defineTileContent({
    id: "close-basic",
    title: "Close Basic",
    summary: "Close only after acceptance evidence and boundary checks agree.",
    body: "Close through the Kernel only for the latest completed Run's current candidate, latest independent PASS with no blockers, all AC evidence, successful hard dependencies and the defined delivery level. Summary or directory archive cannot replace these gates. Load `.pactile/modules/close-basic/contract.md`; report debt and separately authorized next actions without implying unperformed release work.",
    intents: ["exact"],
    inputs: ["verification.evidence"],
    outputs: ["close.outcome"],
    dependencies: ["verify-basic"],
    filesystem: "write",
    process: "execute",
    evidenceDescription: "Link acceptance evidence and the final scoped outcome.",
  }),
  defineTileContent({
    id: "context-progressive",
    title: "Context Progressive",
    summary: "Load only the context needed for the next decision.",
    body: "Use the selected Task's Kernel facts and fingerprinted artifact index, then expand only the needed document sections or source evidence. Registered modules and Tile advice do not grant execution. Do not reconstruct V2 state from legacy files or dump every guide. Load `.pactile/modules/context-progressive/contract.md` for Session Pack budgets and retrieval boundaries.",
    intents: ["exact", "semantic", "structural"],
    inputs: ["request.scope"],
    outputs: ["context.pack"],
    dependencies: ["intake-basic"],
    evidenceDescription: "Reference the current source or task artifact used.",
  }),
  defineTileContent({
    id: "observability-local",
    title: "Observability Local",
    summary: "Record sanitized local execution and decision evidence.",
    body: "Record sanitized local event/result receipts and distinguish measured, estimated and unavailable values. Never persist credentials, raw prompts, sensitive payloads or unrelated user content; local tracing does not authorize external telemetry. Load `.pactile/modules/observability-local/contract.md` when execution or decision evidence must be recorded.",
    intents: ["exact", "structural"],
    inputs: ["execution.result"],
    outputs: ["trace.event"],
    dependencies: ["execute-agent"],
    filesystem: "write",
    evidenceKind: "trace-event",
    evidenceDescription: "Persist a sanitized trace event for the observed action.",
  }),
] as const;

export function loadBaselineTileContent(): ReturnType<typeof loadTileContent> {
  return loadTileContent(BASELINE_TILE_CONTENT);
}
